### ISSUE TITLE
support for environment-specific credentials from encrypted secrets

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/ark-manager#12]
Currently most credentials are referenced via ENV vars.

We should allow setting credentials via the Rails encrypted secrets pattern when the app is in production.

Files that may need to be updated:

- app/services/image_content_service.rb
- app/services/solr_service.rb
- lib/scripts.rb
- config/puma.rb
- config/environments/production.rb
- config/initializers/noid-rails.rb
- config/database.yml.sample
- config/database.yml (check this in?)
- config/cable.yml
- config/solr.yml

**Comment by bbarberBPL** [comment]
Closed after #13 was merged
