### ISSUE TITLE
update logger setting to avoid disk space issues

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/ark-manager#35]
Set logging in staging and production to use rolling logs based on log size.

Make changes to:
* /config/environments/staging.rb
* /config/environments/production.rb

 This pattern should work:
```ruby
# rolling logs, no more than 10 files, 100MB max size each
config.logger = ActiveSupport::Logger.new("#{Rails.root}/log/#{Rails.env}.log", 10, 104_857_600)
```

**Comment by bbarberBPL** [comment]
Closed via cd8c268e1c860b923655dc0bb42bb5328be7ae15
