### ISSUE TITLE
standardize local_original_identifier_type values

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/ark-manager#9]
We should try to standardize the values accepted for `local_original_identifier_type`.

Use this mapping for current values to new:
old | new
----|----
Physical Location | physical_location
Institution Collection Name | institution_collection_name
DSpace Handle | dspace_handle
id_local-accession field | id_local-accession
id_local-other field | id_local-other 
filename | filename
File Name | filename
Filename | filename
Institution Name | institution_name
OAI Header Identifier | oai_header_id
Barcode | barcode
Marc MD5 | marc_md5

**Comment by bbarberBPL** [comment]
We're going to need to add those to the curator ark_params too FYI
